# Generated by Django 3.2.6 on 2021-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficluty',
            field=models.CharField(choices=[('легко', 'легко'), ('средне', 'средне'), ('сложно', 'сложно')], max_length=6, verbose_name='сложность'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=120, verbose_name='название'),
        ),
    ]
